### ISSUE TITLE
[YBState setStateChart:] isn't thread safe

### ISSUE THREAD

**Issue by nikolaykasyanov** [ronaldmannak/YBStatechart#2]
You're using NSEnumerationConcurrent here, but it assumes concurrent block invocation, but [YBStatechart registerState:] modifies NSMutableDictionary, but NSMutableDictionary is not thread safe!

I haven't any problems on iOS, but on Simulator some assertions fails on completely correct state chart, I think this is due to thread unsafety.

**Comment by martijnthe** [comment]
Thanks for reporting this. You're right! My bad.
Would you mind fixing it and sending a pull request?

Thanks.

Martijn

**Comment by nikolaykasyanov** [comment]
Submitted pull request.
Thanks for nice library though.

**Comment by martijnthe** [comment]
Thanks for submitting the issue and fixing it!
