### ISSUE TITLE
Version bump & podspec update

### ISSUE THREAD

**Issue by nikolaykasyanov** [ronaldmannak/YBStatechart#4]
Would you be so kind and create tag 1.02 from current master? I can update podspec if you want in this repo and also in CocoaPods specs repo.

**Comment by ronaldmannak** [comment]
Yes, it's on my list. Thanks for improving the code!

**Comment by nikolaykasyanov** [comment]
Hi, sorry for bothering you, but what about tag & podspec? :) You can only tag, then I'll update pod spec in CocoaPods repository.

**Comment by ronaldmannak** [comment]
Sorry for the delay, just added tag 1.0.2. Thanks again for you help!!

**Comment by nikolaykasyanov** [comment]
Thanks, I updated podspec in CocoaPods spec repo.
